FROM php:8.2

WORKDIR /var/www/html

RUN apt-get update -y && apt-get install -y openssl zip unzip git libonig-dev

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo mysqli pdo_mysql mbstring

COPY . /var/www/html

EXPOSE 8000

CMD ./start.sh
